name: "Setup"
description: "Setup"
inputs:
  registry:
    description: "Registry"
    required: true
  username:
    description: "Username"
    required: true
  password:
    description: "Password"
    required: true

runs:
  using: "composite"
  steps:
    # Setup Go
    - uses: actions/setup-go@v5
      with:
        go-version: "stable"

    # Setup Pnpm
    - uses: pnpm/action-setup@v2
      with:
        version: latest

    # Setup Node
    - uses: actions/setup-node@v4
      with:
        node-version: "24"
        cache: "pnpm"
        cache-dependency-path: '**/pnpm-lock.yaml'

    # Setup ko
    - uses: ko-build/setup-ko@v0.9

    # Login DockerHub 
    - uses: docker/login-action@v3
      with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}