name: "Setup"
description: "Setup"
inputs:
  registry:
    description: "Registry"
    required: true
  username:
    description: "Username"
    required: true
  password:
    description: "Password"
    required: true

runs:
  using: "composite"
  steps:
    # Setup Go
    - uses: actions/setup-go@v5
      with:
        go-version: "stable"

    # Setup ko
    - uses: ko-build/setup-ko@v0.9

    # Login DockerHub 
    - uses: docker/login-action@v3
      with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}