defaultBaseImage: cgr.dev/chainguard/static
defaultLdflags:
  - -s -w
builds:
  - id: custodian
    dir: ./custodian
    main: .
    flags: []
    ldflags:
      - -X main.version={{.Git.ShortCommit}}