configs:
  caddyfile:
    content: |
      {
        auto_https off
      }

      :80 {
        handle_path /api/v1* {
          handle_path /custodian* {
            reverse_proxy custodian:8888
          }
        }
      }

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
  custodian:
    image: ghcr.io/async-lab/asynx/custodian/cmd:latest
    restart: unless-stopped
