name: nightly

on:
  workflow_dispatch:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    uses: ./.github/workflows/template-publish.yml
    secrets: inherit
