name: deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted, asynx]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Deploy
        run: |
          export COMPOSE_PROJECT_NAME=asynx
          docker compose pull
          docker compose up -d
