name: deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: [self-hosted, asynx]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Deploy
        env:
          LDAP_ADDR: ${{ secrets.LDAP_ADDR }}
          LDAP_BIND_DN: ${{ secrets.LDAP_BIND_DN }}
          LDAP_BIND_PASS: ${{ secrets.LDAP_BIND_PASS }}
          LDAP_BASE_DN: ${{ secrets.LDAP_BASE_DN }}
          LDAP_USER_BASE_DN: ${{ secrets.LDAP_USER_BASE_DN }}
          LDAP_GROUP_BASE_DN: ${{ secrets.LDAP_GROUP_BASE_DN }}
          PASETO_SECRET: ${{ secrets.PASETO_SECRET }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_REPLY_TO: ${{ secrets.SMTP_REPLY_TO }}
        run: |
          export COMPOSE_PROJECT_NAME=asynx
          docker compose up -d --pull always --remove-orphans

      - name: Health Check
        run: |
          echo "🔍 正在检查服务健康状态..."

          sleep 5

          # NETWORK=$(docker network ls --filter name=asynx_default --format "{{.Name}}")

          RESPONSE=$(docker run --rm --network asynx_default curlimages/curl -f -v -m 10 http://asynx:8888/api/hello 2>&1)
          CURL_EXIT_CODE=$?

          if [ $CURL_EXIT_CODE -eq 0 ]; then
            echo "✅ 健康检查通过"
          else
            echo "❌ 健康检查失败，详细错误如下："
            echo "========================================"
            echo "$RESPONSE"
            echo "========================================"
            exit 1
          fi
